export { TypicalTransformer } from './transformer.js'
export type { TransformResult } from './transformer.js'
export { loadConfig, validateConfig, defaultConfig } from './config.js'
export type { TypicalConfig, TypicalSourceMapConfig } from './config.js'
export { composeSourceMaps, inlineSourceMapComment, externalSourceMapComment, createIdentityMap, stripSourceMapComment } from './source-map.js'
export type { SourceMapOptions } from './source-map.js'
